version: '3'

services:


  apache:
    container_name: 'apache_web'
    image: httpd:2.4
    ports:
      - "80:80"
      - "443:443"

    links:
      - php72:fpm72
      - php56:fpm56

    volumes:
      - ./conf/apache/:/usr/local/apache2/conf/:rw
      - ./www/:/var/www/html/:rw
      - ./log/apache/:/usr/local/apache2/logs/:rw
      - /etc/localtime/:/etc/localtime
    networks:
      docker_net:
        ipv4_address: ${APACHE_IP}

  nginx:
    container_name: 'nginx_web'
    image: nginx:alpine
    ports:
      - "8080:80"
      - "4343:443"
    volumes:
      - ${WORKSPACES}:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
      - /etc/localtime/:/etc/localtime
    links:
      - php72:fpm72
      - php56:fpm56
    environment:
      - TZ=Asia/Shanghai
    networks:
      docker_net:
        ipv4_address: ${NGINX_IP}
 

  php72:
    container_name: 'php72'
    image: luohua2018/klc-php72
    expose:
      - "9000"
    volumes:
      - ${WORKSPACES}:/var/www/html/:rw
      - ./conf/php/php72.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www72.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
      - /etc/localtime/:/etc/localtime
    links:
      - mysql:mysql
      - redis:redis
    networks:
      docker_net:
        ipv4_address: ${PHP72_IP}

  php56:
    container_name: 'php56'
    image: luohua2018/klc-php56
    expose:
      - "9000"
    volumes:
      - ${WORKSPACES}:/var/www/html/:rw
      - ./conf/php/php56.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www56.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
      - /etc/localtime/:/etc/localtime
    links:
      - mysql:mysql
      - redis:redis
    networks:
      docker_net:
        ipv4_address: ${PHP56_IP}

  mysql:
    container_name: 'db'
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql/:rw
      - ./conf/mysql/conf.d/:/etc/mysql/conf.d/:rw  
      - /etc/localtime/:/etc/localtime
      
    environment:
      MYSQL_ROOT_PASSWORD: "klc1234"

    networks:
      docker_net:
        ipv4_address: ${MYSQL_IP}

  phpmyadmin:
      container_name: 'phpmyadmin'
      image: phpmyadmin/phpmyadmin
      ports:
        - "8001:80"
      environment:
        MYSQL_USER: "root"
        MYSQL_PASSWORD: "root"
        MYSQL_ROOT_PASSWORD: "klc1234"
        PMA_HOST: mysql
      links:
        - mysql:mysql
      networks:
        docker_net:
              ipv4_address: ${MYADMIN_IP}


  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      docker_net:
        ipv4_address: ${REDIS_IP}

  portainer:
    container_name: 'portainer'
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./portainer/:/data:rw
    networks:
      docker_net:
        ipv4_address: ${PORTAINER_IP}

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: "${DOCKER_SUBNET}"
